services:
  - type: web
    name: hill-cipher-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: hill-cipher-backend.onrender.com